//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.ChannelPayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelPayService.ChannelPayServiceSoap")]
    public interface ChannelPayServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Pay(string paytype, string clientID, string clientKey, string terminalID, string strAmmount, string payCode, string subject, string shopID, string oprID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Refund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Refund(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string strAmmount, string terminalID, string oprID, string refundReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelPayServiceSoapChannel : WebTest.ChannelPayService.ChannelPayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelPayServiceSoapClient : System.ServiceModel.ClientBase<WebTest.ChannelPayService.ChannelPayServiceSoap>, WebTest.ChannelPayService.ChannelPayServiceSoap {
        
        public ChannelPayServiceSoapClient() {
        }
        
        public ChannelPayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelPayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelPayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelPayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Pay(string paytype, string clientID, string clientKey, string terminalID, string strAmmount, string payCode, string subject, string shopID, string oprID) {
            return base.Channel.Pay(paytype, clientID, clientKey, terminalID, strAmmount, payCode, subject, shopID, oprID);
        }
        
        public string Refund(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string strAmmount, string terminalID, string oprID, string refundReason) {
            return base.Channel.Refund(paytype, clientID, clientKey, channelOrderNo, orderNo, strAmmount, terminalID, oprID, refundReason);
        }
        
        public string QueryOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID) {
            return base.Channel.QueryOrder(paytype, clientID, clientKey, channelOrderNo, orderNo, terminalID, oprID);
        }
        
        public string CancelOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID) {
            return base.Channel.CancelOrder(paytype, clientID, clientKey, channelOrderNo, orderNo, terminalID, oprID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChannelPayService.ChannelPayServiceSoap12")]
    public interface ChannelPayServiceSoap12 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Pay(string paytype, string clientID, string clientKey, string terminalID, string strAmmount, string payCode, string subject, string shopID, string oprID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Refund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Refund(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string strAmmount, string terminalID, string oprID, string refundReason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelPayServiceSoap12Channel : WebTest.ChannelPayService.ChannelPayServiceSoap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelPayServiceSoap12Client : System.ServiceModel.ClientBase<WebTest.ChannelPayService.ChannelPayServiceSoap12>, WebTest.ChannelPayService.ChannelPayServiceSoap12 {
        
        public ChannelPayServiceSoap12Client() {
        }
        
        public ChannelPayServiceSoap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelPayServiceSoap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelPayServiceSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelPayServiceSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Pay(string paytype, string clientID, string clientKey, string terminalID, string strAmmount, string payCode, string subject, string shopID, string oprID) {
            return base.Channel.Pay(paytype, clientID, clientKey, terminalID, strAmmount, payCode, subject, shopID, oprID);
        }
        
        public string Refund(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string strAmmount, string terminalID, string oprID, string refundReason) {
            return base.Channel.Refund(paytype, clientID, clientKey, channelOrderNo, orderNo, strAmmount, terminalID, oprID, refundReason);
        }
        
        public string QueryOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID) {
            return base.Channel.QueryOrder(paytype, clientID, clientKey, channelOrderNo, orderNo, terminalID, oprID);
        }
        
        public string CancelOrder(string paytype, string clientID, string clientKey, string channelOrderNo, string orderNo, string terminalID, string oprID) {
            return base.Channel.CancelOrder(paytype, clientID, clientKey, channelOrderNo, orderNo, terminalID, oprID);
        }
    }
}
